#version: '3'
#services:
#  database:
#    image: "postgres" # use latest official postgres version
#    environment:
#      - POSTGRES_MULTIPLE_DATABASES=db1,db2
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#    expose:
#      - 5432
#    ports:
#      - 5432:5432
#    volumes:
#      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#volumes:
#  database-data: # named volumes can be managed easier using docker-compose


#version: '3'
#services:
#  database:
#    image: "postgres" # use latest official postgres version
#    env_file:
#      - postgres-database.env # configure postgres env
#    expose:
#      - 5432
#    ports:
#      - 5432:5432
#    volumes:
#      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#volumes:
#  database-data: # named volumes can be managed easier using docker-compose

version: '3'
services:
  pgdb1:
    image: postgres:10
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  pgdb2:
    image: postgres:10
    ports:
      - 5105:5432
    expose:
      - 5105
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kristyl@admin.com
      PGADMIN_DEFAULT_PASSWORD: test1234