version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - postgres-database.env # configure postgres env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose