version: '3'
services:
  mysqsldb1:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost

  mysqsldb2:
    image: mysql:5.7.30
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 5050:8080