version: '3'
services:
  pgdb1:
    image: postgres:10
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  pgdb2:
    image: postgres:10
    ports:
      - 5105:5432
    expose:
      - 5105
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kristyl@admin.com
      PGADMIN_DEFAULT_PASSWORD: test1234